- .travis.yml
- config/prod/AMP-WGS-MSSM-Transfer.yaml
- config/prod/agoradb-bastian3.yaml
- config/prod/amp-emory-bucket.yaml
- config/prod/config.yaml
- config/prod/gates-ki-001-s3bucket.yaml
- config/prod/mpower2-user-add.yaml
- config/prod/raad2-challenge.yaml
- config/prod/test-AMP-Emory-ec2.yaml
- config/prod/test-bsmn-cfncluster-ec2.yaml
- config/prod/test-kdaily-encryptedexternals3.yaml
- config/prod/test-ki-rally-manager-ec2.yaml
- hooks/notify_ec2.py
- hooks/synapse_external_bucket.py
- scripts/DeleteSynapseExternalBucket.sh
- templates/SynapseExternalBucket.yaml
- templates/managed-ec2.yaml
Migrate auto provisioned resources to this repo from scicomp-infra
repo.  Also setup for Travis CI.
> Migrate provisioned resources

- templates/SynapseExternalBucket.yaml
Support additional bucket lifecycle storage class[1]
[1] https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html
> [IT-388] support generic bucket LifeCycle

- config/prod/test-redhatlinux.yaml
This AMI is 8GB built from redhat linux instance
> Test redhat linux

- config/prod/neurolincs-actual.yaml
> New neurolincs instance

- config/prod/test-instance-demo.yaml
> LIVE DEMO:  Do not merge yet!

- .travis.yml
- .yamllint
- config/prod/aacr-interactome-s3website-new.yaml
- config/prod/amp-emory-bucket.yaml
- config/prod/gates-ki-001-s3bucket.yaml
- config/prod/kara-data-curation.yaml
- config/prod/kelsey-dc.yaml
- config/prod/mpnst-analysis-larger.yaml
- config/prod/mpower2-user-add.yaml
- config/prod/neurolincs-actual.yaml
- config/prod/neurolincs.yaml
- config/prod/nf-salmon-rna.yaml
- config/prod/raad2-challenge.yaml
- config/prod/shiny-raadc2.yaml
- config/prod/test-bsmn-cfncluster-ec2.yaml
- config/prod/test-kdaily-encryptedexternals3.yaml
- config/prod/test-ki-rally-manager-ec2.yaml
- config/prod/test-scrna.yaml
It is difficult for humans to validate yaml syntax when reviewing
provisioner scripts. Setup yamllint[1] to automate validation of
yaml syntax on pull requests.
[1] https://github.com/adrienverge/yamllint
> [IT-515] Setup yaml syntax checker

- config/prod/JKG-SciComp-EC2.yaml
- config/prod/JKG-SciComp-S3.yaml
EC2 on SciComp for PHI work Req
> Add SciComp EC2 JKG

- config/prod/genie-vep-update.yaml
Uses encrypted GENIE batch AMI
> GENIE: update vep

- config/prod/kelsey-analysis.yaml
request for ec2 with new format
> Kelsey analysis

- config/prod/kara-win.yaml
To test out the solution in https://sagebionetworks.jira.com/browse/IT-512
> Create windows instance for Kara

- config/prod/minidream-R-env-pub-prod-instance-ec2-alb.yaml
Setup an application load balancer for milen's minidream app.
> ALB for minidream.synapse.org

- config/prod/JKG-SciComp-EC2-CHeav.yaml
Requesting a compute heavy instance to test efficiency versus memory heavy - TWAS
> Add c5 heavy EC2

- config/prod/elevatems_features.yaml
- To extract elevateMS features
- Used the latest Ubuntu AMI (US West Oregon) from http://www.louisaslett.com/RStudio_AMI/
> Request for a Ubuntu instance c4.8xlarge

- config/prod/bsmn-reprocessing-s3-bucket.yaml
A bucket to aid in uploading the reprocessing data to NDA.
> Bsmn reprocessing s3 bucket

- config/prod/kelsey-ami.yaml
Tom copied this ami for me back in April to be able to close our my personal account. 
It is encrypted because it contains PHI.
> instance from ami

- config/prod/kelsey-ami.yaml
The AMI for used for this is ubuntu so we need to use the Ubuntu
example template to provision this instance.
> fix kelsey instance

- config/prod/tom-rstudio.yaml
* Uses ami-0226a8af83fcecb43 found from here: http://www.louisaslett.com/RStudio_AMI/
* Wait until auto encryption of instances is pulled in for this PR to be pulled in
* Need this instance for analysis of GENIE data
> Acquire Rstudio instance

- config/prod/tom-malaria-chal2.yaml
Due to this issue: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/issues/46 I need another instance.
> Add in second malaria instance

- config/prod/tom-genie.yaml
* Add this in to remove other instance
> Add in genie instance

- config/prod/ahayden-testhost-win.yaml
I stopped doing this last week, but am back to it... the AMI ID was wrong last time, but should be good now.
> adding testhost win

- config/prod/ahayden-testhost-win.yaml
Let's try again with the JC agent dependency change
> Add testhost win

- config/prod/CMC-large-s3.yaml
> Cmc s3 new

- config/prod/AMP-Mayo-Sinai-Bucket.yaml
Allow resources in the `computevpc` access to bucket:
amp-mayo-sinai-synapseencryptedexternalbucket-1bmvn8rlwixv2
> [IT-661] resource access to bucket

- .github/PULL_REQUEST_TEMPLATE.md
Setup a PR template[1] for people making PRs to request
resources. Hopefully it will help reduce the confusion around
templates and workflows.
[1] https://help.github.com/en/articles/about-issue-and-pull-request-templates#pull-request-templates
> Setup a PR template

- config/prod/verena-allen-chal.yaml
> Request t3.small instance for Allen DREAM challenge

- config/prod/kelsey-iops.yaml
I increased the volume size and changed the instance type to be better suited for this use case (and save money!)
> Kelsey iops

- config/prod/mpower2-user-add.yaml
should only notify user with info after creating resource, not on
an update.
> fix sceptre notification hook

- config/prod/vbarone-workstation.yaml
> Added workstation for Vanessa

- config/prod/vbarone001.yaml
Requesting instance for myself based on a clone of the templates
> Adding instance for MobileHealth work

- config/prod/htan-data-model-web-ec2.yaml
Request an instance optimized to run a web site with an elastic search backend:
two open ports 8000 and 9200.
> HTAN data model visualization website instance

- config/prod/lheath-ec2.yaml
- config/prod/lheath-t3.yaml
I'm requesting a t3.2xlarge instance for general purpose computing
> Lauraheath

- config/prod/dwebster-scicomp-general.yaml
Using for general compute with potential prod use
> Adds danWebster instance for scicomp

- config/prod/ecmonsen-emorypipeline-ci.yaml
- config/prod/ecmonsen-emorypipeline-lambda.yaml
- templates/ecmonsen-emorypipeline-ci.yaml
Copied templates from sandbox-provisioner, and updated template path and stack parameters for production.
> Add emory pipeline lambda stacks

- config/prod/ahayden-ubuntu-test.yaml
This is to test a script for a hackathon and see if the Canonical published image works with JC.
Passes pre-commit
> Requesting test instance with Canonical's market image

- config/prod/single-hack-multi07.yaml
- config/prod/single-hack-multi08.yaml
- config/prod/single-hack-multi09.yaml
- config/prod/single-hack-multi10.yaml
- config/prod/single-hack-multi11.yaml
- config/prod/single-hack-multi12.yaml
- config/prod/single-hack-multi13.yaml
- config/prod/single-hack-multi14.yaml
> Request UW hackathon instances

- kkdang-genie-compute.yaml
Requesting moderate cpu and mem instance for Rstudio/GENIE
> Requesting instance for GENIE work

- kkdang-genie-compute.yaml
> Bump build

- kkdang-genie-compute.yaml
> Revert "Bump build"

- config/prod/kkdang-genie-compute.yaml
> Using stock Ubuntu AMI

- config/prod/kkdang-genie-compute.yaml
Changing base AMI; requesting for GENIE.
> Reverting to Rstudio AMI

- config/prod/xindi-r-studio.yaml
> Request a R studio instance to run GENIE assessment

- config/prod/xdoan-rstudio.yaml
rstudio instance on server for TESLA analysis (bootstrapping lots of samples)
> rstudio for TESLA

- config/prod/ecmonsen-emorypipeline-lambda.yaml
Oops, I used a wrong setting initally. This is the corrected setting.
> Change to correct SynapseStorageLocationId

- config/prod/nkauer-data-curation.yaml
Title/commit message says it all.
> Request for EC2 with RStudio for amp-ad data curation tasks

- config/prod/ecmonsen-emorypipeline-lambda.yaml
This changes the contents of owner.txt in the Emory pipeline S3 bucket.
> change Synapse user ID (written to owner.txt in bucket) 

- config/prod/phil-udall-superusers.yaml
Upgrade the instance type of an already running instance.
[ ✅] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
> upgrade phil-udall-superusers instance type

- config/prod/ecmonsen-emorypipeline-lambda.yaml
A new storage location has been created with the correct user. This PR updates the setting for the Emory pipeline lambda.
> Update storage location ID for Emory pipeline

- config/prod/cmolitor-data-tasks-ec2.yaml
- config/prod/kara-win.yaml
Quotes around braces makes linting files easier
> linting requires quotes around braces

- config/prod/kkdang-genie-rstudio.yaml
DELETE THIS TEMPLATE BEFORE SUBMITTING
In order to have a good experience with our community, we recommend that
you read the contributing guidelines for making a PR, and understand the
workflow to provision resources:
https://sagebionetworks.jira.com/wiki/spaces/IT/pages/708083719/Sage+AWS+Provisioner
PR Checklist:
[ ] Describe your resource request in your commit message
Example: "Request a memory optimized EC2 to run analysis on amp-ad data"
[ ] Use the latest version of an example template
https://github.com/Sage-Bionetworks/scicomp-provisioner/pulls?utf8=%E2%9C%93&q=is%3Aopen+%22Example+PR%3A%22
[ ] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
> Smaller GENIE machine.

- config/prod/kara-rstudio.yaml
Requesting an instance with RStudio to do some data curation work.
> Add RStudio instance for Kara

- config/prod/mpower2-user-add.yaml
PR Checklist:
✅ Describe your resource request in your commit message
Example: "Request a memory optimized EC2 to run analysis on amp-ad data"
[Not Applicable] Use the latest version of an example template
https://github.com/Sage-Bionetworks/scicomp-provisioner/pulls?utf8=%E2%9C%93&q=is%3Aopen+%22Example+PR%3A%22
✅ Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
> Upgrade instance type of mpower2-user-add

- config/prod/mpower2-user-add.yaml
This instance was created with a very old CFN template.
This updates to using latest templates which should provider
for a smoother user experience.
> update instance using new templates

- config/prod/phil-udall-superusers.yaml
I want to do to this instance what we did to the mpower2-user-add stack yesterday.
> Rebuild phil-udall-superusers

- config/prod/AMP-Mayo-Sinai-Bucket.yaml
Companion to https://github.com/Sage-Bionetworks/aws-infra/pull/239
> [SYNPY-1054] adjust region restriction

- config/prod/kelsey-analysis-2.yaml
> spin up r4.4xlarge instance for CMC analysis

- config/prod/minidream-R-env-pub-prod-instance-ec2-alb-v2.yaml
- config/prod/minidream-R-env-pub-prod-instance-ec2-v2.yaml
This PR adds an ALB resource to tunnel public 443 to the target instance. The instance will need a manual change to its security group as a final step, then manual OS config.
> Rebuild minidream

- config/prod/phil-cough-data.yaml
Create S3 bucket for cough data data transfer.
> add phil-cough-data stack

- config/prod/shinyserver-pro-prod.yaml
This is the instance to run shinyserver-pro production server.
> ShinyserverPro instance production

- config/prod/shinyserver-pro-prod-alb-v2.yaml
Setup a load balancer for the new shinyPro server
> Add load balancer for shinyserver-pro

- config/prod/shinyserver-pro-prod-alb-v2.yaml
Try without 'dependencies' section.
> m-shinypro-alb

- config/prod/ecmonsen-emorypipeline-ci.yaml
- config/prod/ecmonsen-emorypipeline-lambda.yaml
Adding myself as the owner now that I've inherited this project.
> Replace owner email for ecmonsen-emorypipeline-lambda

- templates/htan-synapse-bucket.yaml
Add a cloudformation template to automate deployment of
HTAN buckets that will work with the s3-synapse-sync lambda[1]
[1] https://github.com/Sage-Bionetworks/s3-synapse-sync
Depends on Sage-Bionetworks/s3-synapse-sync#3
> [IT-937] Add cloudformation template for HTAN bucket

- config/prod/s3-synapse-sync.yaml
- config/prod/s3-synpapse-sync.yaml
Deploy s3-synapse-sync lambda into AWS account.
> [IT-937] Deploy s3-synapse-sync lambda

- config/prod/htan-bucket-a.yaml
depends on Sage-Bionetworks/scicomp-provisioner#368
> [IT-937] Create a synapse bucket for HTAN

- config/prod/htan-bucket-a.yaml
- templates/htan-synapse-bucket.yaml
Configure bucket notification to trigger lambda function.
> [IT-937] Setup bucket notification

- templates/htan-synapse-bucket.yaml
Follow on to PR #375 This enables NotificationConfiguration for S3 bucket.
> [IT-937] Enable NotificationConfiguration

- config/prod/s3-synapse-sync.yaml
- data/s3-synapse-sync-bucket-vars.yaml
Redploy lambda with updates for PR
https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/7
> [IT-937] redeploy s3-synapse-sync lambda

- config/prod/s3-synapse-sync-bucket-a.yaml
This is the post step for adding an S3 synapse bucket
in PR https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/379
depends on Sage-Bionetworks/scicomp-provisioner#379
> [IT-937] Enable S3 notifications

- config/prod/s3-synapse-sync.yaml
Update to match change in PR https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/12
depends on Sage-Bionetworks/s3-synapse-sync#12
> [IT-937] pass in KmsDecryptPolicyArn

- config/prod/s3-synapse-sync-bucket-a.yaml
- config/prod/s3-synapse-sync.yaml
- data/s3-synapse-sync-bucket-vars.yaml
Add `BucketNamePrefix` parameter to lambda deployment
> re-deploy s3-synapse-sync lambda

- config/prod/htan-dcc-bucket-a.yaml
> create htan synapse sync bucket

- config/prod/htan-dcc-bucket-a.yaml
Deploy bucket with `EnableNotificationConfiguration: "true"`
@zaro0508 @xdoan
> enable bucket notifications

- data/s3-synapse-sync-bucket-vars.yaml
Change `htan-dcc-bucket-a` to sync to a service-account-created Synapse project
@xdoan @zaro0508
> update htan bucket synapse project ID

- config/prod/htan-dcc-centerA.yaml
- data/s3-synapse-sync-bucket-vars.yaml
Create new s3-synapse-sync bucket, adding service account `SynapseID`
@zaro0508 @xdoan
> create new htan test bucket

- config/prod/htan-dcc-centerA.yaml
Enable bucket notifications for `htan-dcc-centerA`
@zaro0508
> enable bucket notifs

- config/prod/htan-dcc-center-a.yaml
- data/s3-synapse-sync-bucket-vars.yaml
Sorry- forgot bucket names cannot have uppercase characters. Re-creating the previous bucket. 
@zaro0508 @xdoan
> re-create htan bucket

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
* Fix CODOWNERS so that Github reviewers get automatically set when
a new PR is created.
* Update PR template since we are deprecating the GH provisioner for
the service catalog provisioner
> fix GH CODEOWNERS and update PR template

- config/prod/htan-dcc-center-b.yaml
- data/s3-synapse-sync-bucket-vars.yaml
to test s3-synapse-sync lambda with multiple buckets
> Create new bucket

- config/prod/htan-dcc-center-b.yaml
Enable notifications for `htan-dcc-center-b` bucket
> enable s3 notifications

- config/prod/htan-dcc-bu.yaml
- data/s3-synapse-sync-bucket-vars.yaml
Create HTAN bucket for BU
@zaro0508 @xdoan @milen-sage
> create BU bucket

- config/prod/htan-dcc-bu.yaml
Enable notifications for `htan-dcc-bu` bucket
> enable notifications

- config/prod/htan-dcc-ohsu.yaml
- config/prod/s3-synapse-sync.yaml
Create HTAN S3 bucket for OHSU
> create OHSU bucket

- config/prod/htan-dcc-ohsu.yaml
Enable s3 notifications for `htan-dcc-ohsu` bucket
> enable s3 notifs

- config/prod/htan-dcc-bu.yaml
- config/prod/htan-dcc-ohsu.yaml
Update buckets to include Dave Gutman's ARN for DSA access
> add Dave ARN to access HTAN buckets

- config/prod/htan-dcc-ohsu.yaml
adding new collaborator ARN (imaging data project or IDP) for access to bucket to sync files.
> adding new IDP collaborator ARN

- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-tma-tnp.yaml
adding HTAN user to tma-tnp bucket ACL
> Add HTAN collaborator to bucket ACL

- config/prod/htan-dcc-msk.yaml
adding collaborator to HTAN MSK bucket
> add HTAN collaborator to MSK bucket

- config/prod/htan-dcc-msk.yaml
adding HTAN collaborator to MSK bucket
> add MSK collaborator ARN

- config/prod/htan-dcc-msk.yaml
Adding another HTAN collaborator to the MSK bucket
> add HTAN collaborator ARN

- config/prod/htan-dcc-duke.yaml
- config/prod/s3-synapse-sync.yaml
Set up Duke HTAN bucket with synapse sync lambda and add collaborator ARN
> enable notifs for Duke HTAN bucket

- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/s3-synapse-sync.yaml
Creating an HTAN bucket for TNP SARDANA
> add tnp-sardana htan bucket

- config/prod/htan-dcc-tnp-sardana.yaml
> enable notifs for SARDANA bucket

- config/prod/TESLA-download-bucket.yaml
- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
- config/prod/htan-synapse-sync-kms-key.yaml
- config/prod/s3-synapse-sync.yaml
This PR moves ownership of TESLA resources to James due to offboarding.
Passes pre-commit. 
Will close https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/431
@zaro0508 please confirm that bucket SynapseUserName changes are not destructive.
> Change owner and permissions

- config/prod/ecmonsen-emorypipeline-ci.yaml
- config/prod/ecmonsen-emorypipeline-lambda.yaml
This transfers ownership of the Emory data upload lambda to @tthyer
> Transfer Emory pipeline to Tess

- config/prod/htan-dcc-hms.yaml
- config/prod/s3-synapse-sync.yaml
- add HTAN collaborator to HMS bucket
- set up HMS bucket with s3-synapse-sync lambda
> Enable notifs for HMS HTAN bucket

- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
Hi hello, I'm requesting general user access to all of the HTAN s3 buckets.
I currently have the `sandbox-developer` role.
Please let me know if I've done anything incorrectly.
> Request general user access to htan s3 buckets.

- config/prod/AMP-Emory-Bucket.yaml
Added myself to the access list for the AMP-Emory bucket. I don't know if Phil's role exists anymore; at the very least, he can't see this bucket. Let me know if I need to update his role, as well.
> Add Nicole Kauer to AMP-Emory-bucket access list

- config/prod/dian-uat-hm-migration-s3.yaml
The source ip restriction in the same-region access policy seems to be problematic. This also pegs the additional ARN string to a session with my user, which could also have been an issue.
> IT-1208.post revise access control for Synapse link

- config/prod/AMP-Emory-Bucket.yaml
This reverts commit fc909cdb3ec267b3568d81ff6ef488819063bf60.
Revert change that failed to deploy, https://travis-ci.com/github/Sage-Bionetworks/scicomp-provisioner/jobs/510050716#L551 ...
```
prod/AMP-Emory-Bucket ExternalBucketPolicy AWS::S3::BucketPolicy UPDATE_FAILED Invalid principal in policy
```
> Revert "Add Nicole Kauer to access list (#467)"

- config/prod/AMP-Emory-Bucket.yaml
adding Nicole to AMP-Emory-Bucket
> adding Nicole to AMP-Emory-Bucket

- config/prod/AMP-Emory-Bucket.yaml
> Add nkauer access amp emory bucket

- config/prod/AMP-Emory-Bucket.yaml
- config/prod/JKG-SciComp-S3.yaml
- config/prod/TESLA-download-bucket.yaml
- config/prod/amp-mayo-sinai.yaml
- config/prod/usage-statistics-S3.yaml
- config/prod/veoibd-s3.yaml
We switched from SAML integration to SSO which uses a different role
for federated user access.  We update with the new SSO role.
> update reesouce access fpr SSO

- config/prod/htan-synapse-sync-kms-key.yaml
We've switched from using JC AWS SAML integration to AWS SSO so
we need to update the reference to the role.
> Replace SAML reference with SSO

- config/prod/dian-prod-hm-migration-s3.yaml
- config/prod/dian-uat-hm-migration-s3.yaml
Add Bruce Hoff as accessor of DIAN buckets
> IT-1208:  Add Bruce Hoff as accessor of DIAN buckets

- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
- config/prod/s3-synapse-sync.yaml
In this PR, I'm updating the HTAN buckets as follows:
- Use `v1.5.0` of the template to grant contributors with access to the bucket policy
- Revoke access to buckets for collaborator 
I'm marking this PR as a draft to prevent it from being merged prematurely. Once I hear back that the collaborator no longer needs access, I'll mark the PR as ready for a merge.
> Update HTAN buckets

- config/prod/veoibd-s3.yaml
This reverts commit 92390915a010df223ed4198c51e196c72c497224.
The file is for S3 bucket, not EC2 instance
> Revert "Remove Cindy's instance (#493)"

- config/prod/htan-dcc-tnp-sardana.yaml
Add Allie Creaons's IAM role to the S3UserARNs and DenyDeleteARNs list in the htan-dcc-tnp-sardana S3 bucket template
> [IT-1475] Add Allie Creason existing IAM role to read write access on tnp sardana bucket

- config/prod/htan-dcc-center-a.yaml
@clarisse-lau: This PR can serve to test these two PRs:
- https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/41
- https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/40
> Test `s3-synapse-sync` v1.5.1

- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
@adamjtaylor is planning on running some Nextflow workflows in Tower. This PR grants the relevant IAM roles with access to the HTAN buckets, thereby obviating the need to copy large amounts of data into the Tower bucket.
> Grant Tower with access to HTAN buckets

- config/prod/psorcast-ec2.yaml
This was a request from @DanWebster and @vjbytes102
> [IT-1519] provision a p2.xlarge EC2 for psocast

- config/prod/htan-dcc-duke.yaml
Adding collaborators Alex Sibley and Marissa Lee to the HTAN Duke bucket and revoking access for Jeremy Gresham, who is no longer with the group
> add collaborator to HTAN Duke bucket

- config/prod/htan-dcc-center-a.yaml
An attempt to fix the issue described here: 
https://sagebionetworks.slack.com/archives/CEFQD0KU1/p1639774944448300
> Switch to HTTP template handler

- config/prod/htan-dcc-center-a.yaml
> Remove sneaky space

- config/prod/EC2-gene-co-expression.yaml
requested by @jgockley62 
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/334
> [IT-1636] EC2 instance for gene co-expression network

- config/prod/htan-dcc-stanford.yaml
- config/prod/s3-synapse-sync.yaml
Configuring the HTAN Stanford bucket with synapse sync lambda, and granting access to collaborator Daniel Cotter
> Enable Stanford S3 bucket notifs

- .pre-commit-config.yaml
Use Sceptre's sceptrelint[1] pre-commit linter to check
scptre stack configs for correctly defined templates
[1] https://github.com/Sceptre/sceptrelint
> [IT-1531] Use pre-commit sceptrelint

- config/prod/EC2-gene-co-expression-3.yaml
- config/prod/EC2-gene-co-expression-4.yaml
- config/prod/EC2-gene-co-expression-5.yaml
- config/prod/EC2-gene-co-expression-6.yaml
- config/prod/EC2-gene-co-expression-7.yaml
- config/prod/EC2-gene-co-expression-8.yaml
- config/prod/EC2-gene-co-expression-9.yaml
@jgockley62 requests for more instances for his data
processing.
> Provision gene-coexpression instances

- .pre-commit-config.yaml
Update all pre-commit linter versions.
> update pre-commit linters

- config/prod/PsychENCODE-Globus-S3.yaml
Update with template that switches from BucketOwnerPreferred
to BucketOwnerEnfored to disable ACLs.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/351
> [IT-2075] update S3 bucket template

- config/prod/nf-syn23664726-s3.yaml
Use new identity-central account for nf-syn23664726 bucket
> [IT-1967] Update bucket access

- config/prod/htan-dcc-msk.yaml
PR to give HTAN collaborator Sam Rose access to MSK bucket
> add user to MSK HTAN bucket

- config/prod/usage-statistics-S3.yaml
We now have a need to support deployments to multiple AWS regions. Change to the CI system to accomodate multi-region deployments.
> Refactor CI deployment for multiple regions

- config/prod/htan-dcc-chop.yaml
- config/prod/s3-synapse-sync.yaml
Setting up the lambda sync function for the HTAN CHOP bucket
> enable lambda sync for CHOP bucket

- config/prod/nf-syn23664726-s3.yaml
Adding bucket access for external collaborator (person in data contributor's lab).
> Add stanford bucket access

- config/prod/psorcast-ec2.yaml
Remove resources provisioned by Vijay since he is no longer at Sage
> Offboarding Vijay

- config/prod/minidream-rstudio-2023-ec2-alb.yaml
- config/prod/minidream-rstudio-2023-ec2.yaml
Project and Department tags cannot contain spaces. 
we remove them with an updated template
> remove department and project tags

- config/prod/htan-dcc-stanford.yaml
This PR adds a new user ARN from the HTAN Stanford center to the HTAN Stanford bucket.
> Add user to HTAN Stanford bucket

- config/prod/amp-mayo-sinai.yaml
- config/prod/gates-ki-001.yaml
- config/prod/nf-syn23664726-s3.yaml
Enable bucket life cycle for buckets:
* amp-mayo-sinai-synapseencryptedexternalbucket-1bmvn8rlwixv2
* nf-syn23664726-s3-bucket-n9uakf7bowwd
* gates-ki-001-synapseencryptedexternalbucket-kl8vu7tqto1b
> [IT-2859 & IT-1505] Enable bucket life cycle

- config/prod/recover-s3-bucket.yaml
Reverts Sage-Bionetworks/scicomp-provisioner#590
> Revert "Update recover-s3-bucket.yaml"

- config/prod/htan-dcc-msk.yaml
Adding data contributor Andrew Moorman to the MSK S3 bucket
> add user to htan msk bucket

- config/prod/TESLA-download-bucket.yaml
update the inline yaml based region restriction lambda with a properly implemented, packaged and versioned lambda for the TESLA bucket.
> [IT-2794] fix region restriction lambda for TESLA bucket

- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
This PR gives access to my  (Adam Taylor's) TowerViewer role for the HTAN buckets provisioned here.  
This is needed to facilitate outputs from Nextflow Tower runs into HTAN buckets.
> Add Adam's TowerViewer role to HTAN buckets

- config/prod/s3-synapse-sync.yaml
Deploy dependabot security updates for the s3-synapse-sync lambda.
> [IT-2892] Security updates for s3-synapse-sync

- config/prod/ecmonsen-emorypipeline-ci.yaml
- config/prod/ecmonsen-emorypipeline-lambda.yaml
Tess has left a long time ago.  Assigning ownership of emory pipeline resources to Abby.
> change ownership of emory pipeline

- config/prod/gates-ki-001.yaml
- config/prod/mep-lincs-s3.yaml
Larsson has left the building. Assigning ownership of meps lincs and gates ki buckets to Tom.
> change ownership of S3 buckets

- config/prod/htan-synapse-sync-kms-key.yaml
- templates/htan-synapse-sync-kms-key.yaml
A direct ImportValue dependency in a template makes it a hard dependency which makes it difficult to update. This changes the dependency to be more easily updateable.
> Remove hard dependency

- config/prod/cmc-migration-bucket.yaml
Setup temporary S3 bucket for Common Mind Consortium data migration.
> add cmc migration bucket

- .pre-commit-config.yaml
Check jinja templates using a jinja linter
> [IT-3396] Use jinja linter

- config/prod/htan-dcc-casi-tnp.yaml
- config/prod/htan-dcc-center-a.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
Adding a user to HTAN DCC buckets
> Adding user to HTAN S3 bucket configs

- config/prod/veoibd-s3.yaml
i installed pre-commit and the hook ran before this commit. All tests passed or were skipped
> add Jess Vera to Grant Access list for veoibd usa bucket

- config/prod/VEOIBD-S3-USA.yaml
- config/prod/veoibd-s3.yaml
- revert PR #638
- add Jess to correct GrantAccess list
thank you for merging @zaro0508
> add Jess Vera to GrantAccess list for veoibd usa bucket

- config/prod/nf-syn53689508-s3.yaml
This PR uses https://github.com/Sage-Bionetworks/aws-infra/pull/415 to update user permissions in a Synapse bucket.
> Update template to fix user permissions in Synapse buckets

- config/prod/htan-dcc-casi-tnp.yaml
- config/prod/htan-dcc-chop.yaml
- config/prod/htan-dcc-dfci.yaml
- config/prod/htan-dcc-duke.yaml
- config/prod/htan-dcc-hms.yaml
- config/prod/htan-dcc-msk.yaml
- config/prod/htan-dcc-ohsu.yaml
- config/prod/htan-dcc-pcapp.yaml
- config/prod/htan-dcc-stanford.yaml
- config/prod/htan-dcc-tma-tnp.yaml
- config/prod/htan-dcc-tnp-sardana.yaml
- config/prod/htan-dcc-vanderbilt.yaml
Requesting to be added to relevant HTAN buckets in AWS.
> DYP access to HTAN AWS bucket requrst.

- .pre-commit-config.yaml
Update pre-commit linter to update monthly, by default it's set to weekly[1].
[1] https://pre-commit.ci/#configuration-autoupdate_schedule
> Change pre-commit auto update schedule

- .github/workflows/deploy.yaml
- .pre-commit-config.yaml
work around for https://github.com/pre-commit-ci/issues/issues/241
> Skip running pre-commit.ci

- templates/htan-synapse-sync-kms-key.yaml
This PR remediates CIS 3.8 'Ensure rotation for customer created CMKs is enabled', see https://sagebionetworks.jira.com/browse/IT-4142.
> IT-4142: Enable key rotation

- DeprecatedProgramCodes.json
- config/prod/TESLA-download-bucket.yaml
Pass the ownership of `TESLA-download-bucket` on to Susheel Varma now that James Eddy is no longer with Sage.
> [IT-3834] Remove James Eddy as bucket owner
