Sage-Bionetworks/scicomp-provisioner

templates/managed-ec2.yaml

Allow provisioning new m5 instances[1]
[1] https://aws.amazon.com/ec2/instance-types/

allow provisioning m5 instances

---

templates/SynapseExternalBucket.yaml

This changes the default bucket encryption from false to true to reduce the chance that someone will place HIPAA-affected data into a bucket unencrypted by mistake.  Our tests show virtually no performance impact of encrypting files at rest.

IT-377 Update SynapseExternalBucket.yaml

---

config/prod/test-AMP-Emory-ec2.yaml
templates/managed-ec2-v2.yaml

Allow SSH access to public and private EC2 instances. This will allow
users to access public instances using a valid SSH keypair.
This does not affect private instances because they are still deployed
to a private subnet. Private instances are still only accessible
after logging into the Sage VPN.
Note: We cannot add this change to the current template because
cloudformation will want to terminate existing instances and
create new ones.  This will blow away existing intances that
people have already provisioned.  To work around this issue
we need to rev the template version and deprecate the existing
one.

Fix access to public EC2 intances

---

README.md
templates/managed-ec2-v3.yaml

Setup scicomp provisioner to deploy an EC2 with an encrypted boot
volume by default.
Note- this is supported on v3 version of the ec2 provisioning template.

[PLFM-5223] use AMI with encrypted volume by default

---

templates/managed-ec2-v4.yaml

The policy[1] that we use to integrate with ParkMyCloud[2]
requires a parkmycloud=yes tag to allow the service
to start and stop any resources on AWS.
[1] https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/ParkMyCloud.yaml#L74
[2] https://www.parkmycloud.com

[IT-433] tag for park my cloud

---

templates/managed-ec2-v3.yaml
templates/managed-ec2-v4.yaml
templates/managed-ec2.yaml

New AWS cloudformation linter rules don't like hi1.4xlarge
and cg1.4xlarge instance types. I'm not sure why but we
can remove them to satisfy the linter because we don't use them.

update template for new linter rules

---

templates/managed-ec2-v4.yaml

c5 has already been enabled on sandbox ec2 template this is
to enable in scicomp as well.

add c5 instance types

---

config/prod/amp-emory-bucket.yaml
config/prod/gates-ki-001-s3bucket.yaml
templates/SynapseExternalBucket-v2.yaml

This is to setup cross account access[1]. Add a parameter to
allow the provisioner to specify which account, group and user
can have access to the provisioned bucket. It is not a required
parameter, if nothing is specified then no access will be given.
[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example2.html

Option to grant access to bucket

---

.travis.yml

Some AWS resources, like cloudfront, can take a long time to deploy
without logging status to the console.  We increase travis_wait[1]
so the build won't timeout and fail.
[1] https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

Increase travis wait time

---

.travis.yml

Use lint_stack[1] to validate the following items for newly
provisioned stack name:
1. stack name contains valid characters.
2. stack name is not a duplicate of existing stack names.
[1] https://github.com/Sage-Bionetworks/infra-utils/blob/master/ci/lint_stack.sh
fde8f8f

[IT-506] lint newly provisioned stack name for errors

---

templates/managed-ec2-v6.yaml

Call a nested template to enable a daily EC2 backup using the Data
Lifecycle Manager[1].  Provisioners have the option to enable or
disable the backup.
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html

[IT-520] Provide option to backup EC2

---

config/prod/AMP-Mayo-Sinai-Bucket.yaml

Service account needs access to migrate MSSM bucket data.

give service account access to bucket

---

config/config.yaml
templates/managed-ec2-v6.yaml

All provisioning using the new template
Sage-Bionetworks/aws-infra/templates/managed-ec2-v7.yaml
will need to set these params
```
template_path: remote/managed-ec2-v7.yaml
AMIId: {{stack_group_config.default_ami}}
KeyName: {{stack_group_config.default_key_pair}}
VpcName: {{stack_group_config.default_vpc}}
hooks:
before_create:
- !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v7.yaml --create-dirs -o templates/remote/managed-ec2-v7.yaml"
before_update:
- !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v7.yaml --create-dirs -o templates/remote/managed-ec2-v7.yaml"
after_create:
- !ec2_notify "{{stack_group_config.aws_account_name}} …
```

[IT-488] Use shared EC2 provisioner template

---

config/config.yaml

Creating Windows AMIs requires additional prep.  Had to recreate
the default windows AMI with Sysprep[1]
[1] https://aws.amazon.com/premiumsupport/knowledge-center/sysprep-create-install-ec2-windows-amis/

Recreate new windows AMI

---

config/config.yaml

The provisioner failed to provision Ubuntu instances with the current
default ubuntu AMI.  Created a new ubuntu AMI with an encrypted root
volume based off of ami-0a313d6098716f372.  We switch to this new
one to provision ubuntu instances.

Update default ubuntu AMI

---

config/prod/minidream-R-env-pub-prod-instance-ec2.yaml

Provision RStudio environment to use for
1) final preparations for the 2019 miniDREAM course
2) production environment for the miniDREAM course
Instance will run RStudio along with its public web interface allowing access to an R environment
for about 20 users on the same machine.
Users will perform calculations on datasets, loading potentially dozens of GBs of data in memory, concurrently. No PHI data will be stored here.
Requested instance: r4.16xlarge

Provision RStudio environment to use for miniDREAM course

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

An earlier PR used a bucket in the wrong AWS account. This should fix it.

Update storage location to one using a bucket in the scicomp account

---

config/prod/usage-statistics-s3.yaml

This grants access to more users to data queried and stored from the data warehouse to support historical usage query reports (for timeframes greater than 6 months ago). Request for these individuals was requested from @larssono.

change owner and add individuals access to bucket

---

config/prod/usage-statistics-s3.yaml

This grants access to more users to data queried and stored from the data warehouse to support historical usage query reports (for timeframes greater than 6 months ago). Request for these individuals was requested from @larssono.

add nicole

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

The ecmonsen-emorypipeline-lambda-code[1] was previously being deployed
to a bucket in org-sagebase-sandbox account.  We have now changed it to
deploy to a bucket in org-sagebase-scicomp account.  Also a new version
was created.  Redirect references to the new bucket.
[1] https://github.com/Sage-Bionetworks/ecmonsen-emorypipeline-lambda-code

update references to ecmonsen lambda

---

config/prod/minidream-R-env-pub-prod-instance-ec2-v2.yaml

We've had a request to rebuild the rstudio instance for minidream. This PR is to create the instance, which I've based on the same parameters as the prior request, and will be followed up with a PR to create an ALB to front the instance. We'll add an nginx local proxy and configure rstudio manually after  the infra builds.

Rebuild minidream server

---

config/prod/minidream-R-env-pub-prod-instance-ec2-v2.yaml

I believe I used the wrong AMI, which caused provisioning to fail. This uses the packer-ubuntu image instead.

Rebuild minidream

---

config/prod/mep-lincs-s3.yaml

Note that the `SynapseUserName` is not changed and should be adjusted later once it's known how to manage that.

change owner to larsson omberg

---

config/prod/AMP-Mayo-Sinai-Bucket.yaml
config/prod/JKG-SciComp-S3.yaml
config/prod/amp-emory-bucket.yaml
config/prod/usage-statistics-s3.yaml
config/prod/veoibd-s3.yaml

Now that we only allow access to AWS thru jumpcloud we need to
update all the GrantAccess configuration in S3 Buckets to the
new assumed role ARN

[IT-922] Update GrantAccess config for S3 buckets

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

Our collaborators at Emory would like to use a different source account and bucket for replication.

Update source account ID for incoming data from Emory

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

Deploy the updated lambda at Sage-Bionetworks/ecmonsen-emorypipeline-lambda-code
to pick up changes in PR https://github.com/Sage-Bionetworks/ecmonsen-emorypipeline-lambda-code/pull/11

Update ecmonsen emorypipeline lambda version

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

Our contact at Emory needs to upload data for a publication under his old account. Previously I had updated the bucket to accept data from a new account that's being created, but they haven't yet finished migrating him to the new account and this dataset needs to be uploaded in the meantime. So I'm reverting that change, and will have to re-revert it later.

Revert source account ID for incoming data from Emory (temporarily)

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

This is a followup to #356; our colleagues at Emory have finished uploading the dataset they needed to upload under the old account, so now I'm changing the source account here to the new one.

Change source account for Emory, again

---

config/prod/htan-synapse-sync-kms-key.yaml
templates/htan-synapse-sync-kms-key.yaml

The S3 Synapse Sync project[1] needs to store secrets in the
AWS SSM. This will create a KMS key to allow us to store those
secrets. The only users that will have access to the key are
AWS account admins and CI systems.
[1] https://github.com/Sage-Bionetworks/s3-synapse-sync

[IT-937] Setup KMS key for HTAN S3 Synapse Sync

---

config/prod/htan-bucket-a.yaml
templates/htan-synapse-bucket.yaml

The strategy for this fix attempt is to deny S3UserARNs
who do not provide canonical account IDs. This works
because S3UserARNs are the only users that have access
to the bucket anyways.
The Previous attempt to fix owner.txt file update with
BucketServiceRoleId condition failed so we remove it..

[IT-937] Fix bucket policy

---

templates/htan-synapse-bucket.yaml

The previous build failed because the NotificationConfiguration requires
a `AWS::Lambda::Permission` which has not been setup yet.  When
attempting to add that permission and NotificationConfiguration at the
same time we run into a circular dependency problem which is documented
in the NotificationConfiguration docs[1].
The doc is basically saying that the only way to avoid the circular
dependency is to deploy in two steps.  The imnplication is that every
time we create a bucket we would need to deploy the AWS::Lambda::Permission
first then run another deploy to setup the NotificationConfiguration.
This step is o setup the permission.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html

[IT-937] add required AWS lambda permission

---

config/prod/s3-synapse-sync.yaml

The single quotes wrapping the string appear as literals in the resulting env var value, which I think may be causing an issue when reading it as a dictionary with json.loads()
@zaro0508 @xdoan

remove quotes from BucketVariables parameter

---

config/prod/htan-dcc-msk.yaml

This reverts commit 0093e5b7a47f24a3e762396845bd72f7f59467a8.
the ARN "arn:aws:iam::583643567512:mfa/jchan" is invalid.

Revert "add HTAN collaborator to MSK bucket (#419)"

---

config/prod/dian-uat-hm-migration-s3.yaml

Add admin SSO role for manual Synapse file_handle linking

---

config/prod/AMP-Emory-Bucket.yaml

AWS reports that 'arn:aws:iam::743849566882:user/dduong' is no
longer a valid principal which caused the CI deployment to fail.
We remove this principal to fix the deployment.
From AWS...
```
Invalid principal in policy (Service: Amazon S3; Status Code: 400;
Error Code: MalformedPolicy; Request ID: 0G10HESHZRCRNJ70;
S3 Extended Request ID: 7+tqQX7+p4+AIEKRRQcg1L9WfMXJvex2R5uM6H5qQaUxUBSGFvd1SMhgUdUjpqYg466qRN5OwVI=;
Proxy: null)
```

Remove user reference

---

config/prod/minidream-rstudio-2021-ec2-alb.yaml
config/prod/minidream-rstudio-2021-ec2.yaml

I'm deploying infrastructure for miniDREAM 2021. This stack is composed of a high-memory EC2 instance in a private subnet behind by a public load balancer (both using existing aws-infra templates). 
We will be hosting RStudio on port 8787 of this instance, and we will setup an nginx reverse proxy to redirect incoming HTTPS (port 443) traffic from the ALB to port 8787. The ALB will take care of upgrading HTTP (port 80) traffic to HTTPS (port 443). 
We have a custom setup to integrate with Synapse evaluation queues, so we can't use the RStudio packer AMI.

Provision miniDREAM 2021 infrastructure

---

config/prod/minidream-rstudio-2021-ec2-alb.yaml

I'm using [this](https://github.com/Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra/blob/main/config/common/nextflow-forge-service-user.yaml#L6-L9) as a working example.

Change `stack_output` to `stack_output_external` for miniDREAM 2021 ALB

---

config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml

I have added ARN entries to provide me with access to 12 HTAN-associated buckets, following the format used by @hweej in #464.  I will be supporting imaging related work for HTAN.
There is an open [JIRA ticket](https://sagebionetworks.jira.com/browse/IT-1274) requesting I be given the `sandbox-developer` role, but I'm not sure this is required as I have used the role-sessions ARNS per @BrunoGrandePhD in 53e61e3.
Hopefully I've done this correctly! Thanks!

Request general user access to HTAN S3 buckets

---

.travis.yml

Travis is cacheing templates which can sometimes cause resources
to provision with old templates.  We delete the foler containing
downloaded templates to force travis to downlod them on every
deployment.

[IT-1295] fix travis deployment

---

config/prod/dian-prod-hm-migration-s3.yaml
config/prod/dian-uat-hm-migration-s3.yaml
config/prod/minidream-rstudio-2021-ec2-alb.yaml
config/prod/minidream-rstudio-2021-ec2.yaml

wget when used without the `-O` option will not download
a file if it already exists.  Since we have multiple
sceptre templates referencing different versions of a CFN
template it can download the 1st version then not download the
2nd version.
For example:
assume the following:
* config/prod/a.yaml references v1.0 of x.yaml CFN template
* config/prod/b.yaml references v2.0 of x.yaml CFN template
workflow:
* sceptre runs config/prod/a.yaml and downloads v1.0 of x.yaml
* sceptre runs config/prod/b.yaml but does not download v2.0 of x.yaml
becuase v1.0 of x.yaml already exists.  sceptre will deploy with the old v1.0 of x.yaml
To force wget to download and overwrite the file we need to use
the `-O` option.

[IT-1295] Fix sceptre template refernces

---

config/prod/dian-uat-hm-migration-s3.yaml

Our hypothesis is that multiple stacks, running in parallel, download different versions of  `s3-bucket-v2.js` to the same local file, creating a collision or race condition in which one stack uses the template downloaded by another stack.  By giving the downloaded file a unique name we seek to eliminate the collision.

IT-1208 fixing hypothesized collision in downloaded files

---

config/prod/htan-dcc-tma-tnp.yaml

Our HTAN collaborator is requesting that we add the `idp-import` IAM user to the `htan-dcc-tma-tnp` S3 bucket.

Add `idp-import` to `htan-dcc-tma-tnp` bucket

---

config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml
config/prod/s3-synapse-sync.yaml

Deploying the change introduced in Sage-Bionetworks/s3-synapse-sync#44, which switches the object ownership setting to `BucketOwnerEnforced`, for all HTAN S3 buckets
(@BrunoGrandePhD)

Switch HTAN buckets to `BucketOwnerEnforced`

---

config/prod/AMP-Emory-Bucket.yaml
config/prod/JKG-SciComp-S3.yaml
config/prod/TESLA-download-bucket.yaml
config/prod/aacr-interactome-s3website-new.yaml
config/prod/amp-mayo-sinai.yaml
config/prod/belltown-solly-2019.yaml
config/prod/ecmonsen-emorypipeline-ci.yaml
config/prod/ecmonsen-emorypipeline-lambda.yaml
config/prod/gates-ki-001.yaml
config/prod/htan-synapse-sync-kms-key.yaml
config/prod/mep-lincs-s3.yaml
config/prod/psorcast-ec2.yaml
config/prod/shinyserver-pro-prod-alb-v2.yaml
config/prod/shinyserver-pro-prod.yaml
config/prod/usage-statistics-S3.yaml
config/prod/veoibd-s3.yaml

Sceptre supports template handlers[1] to get remote templates so we no
longer need to use hooks.  Convert all hooks to template handler.
[1] https://docs.sceptre-project.org/dev/docs/template_handlers.html

Use sceptre template handlers

---

config/prod/EC2-gene-co-expression-2.yaml

This fixes an EC2 that was provisioned with a bad CFN template
(`EC2-gene-co-expression.yaml`).  Once verified we will remove
EC2 from `EC2-gene-co-expression.yaml` template.

[IT-1748] fix EC2

---

config/prod/minidream-rstudio-2022-ec2-alb.yaml
config/prod/minidream-rstudio-2022-ec2.yaml

This PR is related to the issue here [#issue](https://github.com/Sage-Bionetworks/minidream-r-env/issues/22). This stack is composed of a high-memory EC2 instance in a private subnet behind by a public load balancer (both using existing aws-infra templates). This instance will provide RStudio environment for 20-30 students taking miniDream courses. 
Based on Bruno's comment below, the size of instance that we need is: x2gd.8xlarge (32 vCPUs / 512 GiB )
*Note*: This PR is based on the PR in previous year [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files). More context could also be found [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/478)
We have run `pre-commit` for our files: 
```
(venv) lpeng@w153 scicomp-provisioner % pre-commit run …
```

create mini dream 2022 ec2 and alb

---

config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml

This PR adds the `idp-import` IAM user to certain HTAN S3 buckets. This user is owned by Jeremy Muhlich, our HTAN IDP collaborator at HMS and will be used to import data to the [HTAN IDP OMERO instance](https://idp.tissue-atlas.org/) hosted by HMS.

Add `idp-import` user to HTAN S3 buckets

---

.pre-commit-config.yaml

Use the new precommit linter to validate that the assigned CostCenter
tags are valid.
depends on https://github.com/Sceptre/sceptrelint/pull/6

[IT-1531] Use sceptrelint validate stack tags

---

config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml

This PR is partially motivated by IT-1967 and partially motivated by the need to inspect the bucket policy, which can only be done by IAM identities within the same account as the S3 bucket. As a result, my current sandbox role doesn't have access to the bucket policy. Since I have access to the viewer role in scicomp, I was thinking of granting access to my specific assumed-role at the resource/bucket level. If this works, then we can migrate others to using the same viewer role to administer/access the HTAN buckets.

Switch to scicomp role for administering HTAN buckets

---

config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml
config/prod/s3-synapse-sync.yaml

In this PR, I perform the following: 
- I update the `s3-synapse-sync` stack so I can access the bucket policies
- This depends on Sage-Bionetworks/s3-synapse-sync#45 as well as a new tag (`v1.6.1`) once it's merged
Depends on Sage-Bionetworks/s3-synapse-sync#45
----
**Edit:** The following changes were reverted and will be made in a separate PR once IT-1967 is settled. 
- I remove Jason Hwee from the bucket policies since he's no longer a Sage employee
- I update Adam's AWS identity to the scicomp `viewer-plus` role (like what I did for mine in #530)
- This depends on [IT-2049](https://sagebionetworks.jira.com/browse/IT-2049)

Upgrade HTAN s3-synapse-sync stack and avoid sandbox roles

---

config/prod/s3-synapse-sync.yaml

The `s3-synapse-sync.yaml` is the generated lambda template from
the s3-synapse-sync[1] repo.  That generated lambda file is not
committed to git, it is generated then deployed to the
`admincentral_cf_bucket` therefore the template must be referenced
from that bucket.
[1] https://github.com/Sage-Bionetworks/s3-synapse-sync

Fix s3-synapse-sync lambda path reference

---

config/prod/nf-syn23664726-s3.yaml

I would like to provision an S3 bucket to store data for a project on synapse (syn23664726). 
I will need to add external contributors to this bucket, but I don't currently have their ARNs. Can I merge this PR and then update the file to update the bucket once I have the ARNs?

external S3 bucket for syn23664726

---

README.md

Just a minor link change to make it easier to find the example PRs (they are all closed now).

fix link in docs

---

config/prod/PsychENCODE-Globus-S3.yaml
config/prod/nf-syn23664726-s3.yaml
config/prod/nf-syn28545963-s3.yaml
config/prod/recover-s3-bucket.yaml

This updates the template for buckets in the scicomp-provisioner with changes
from https://github.com/Sage-Bionetworks/aws-infra/pull/359
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/359

Update template for S3 buckets

---

config/prod/nf-syn28545963-s3.yaml

NCBI data delivery account no longer needs access to this bucket.

remove NCBI access from bucket

---

config/prod/VEOIBD-S3-USA.yaml

This is a PR to replace the synapse id for sceptre_user_data for VEOIBD USA S3 bucket

replace synapse id for sceptre_user_data

---

.travis.yml

* Sceptre will fail if no config files are defined which should not be a failing condition in the context of CI deployments.  We add a check to deploy infra only if there are stacks to deploy to prevent a CI failure.
* Add --prune flag to automate the Sceptre deletion of stacks via the obsolete parameter[1]
Note: This is the same change as https://github.com/Sage-Bionetworks/sandbox-provisioner/pull/419
[1] https://docs.sceptre-project.org/latest/docs/faq.html#my-ci-cd-process-uses-sceptre-launch-how-do-i-delete-stacks-that-aren-t-needed-anymore

Handle no sceptre stack in CI deployments

---

config/prod/recover-s3-bucket.yaml

**Purpose:** To complete [ETL-318](https://sagebionetworks.jira.com/browse/ETL-318). The role policy and permissions can be found here: [recover/main/templates/glue-job-role.yaml](https://github.com/Sage-Bionetworks/recover/blob/main/templates/glue-job-role.yaml#L70-L80)
PR Checklist:
[X] Clearly explain your change with a descriptive commit message
[X] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
[ETL-318]: https://sagebionetworks.jira.com/browse/ETL-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETL-318] add access to recover bucket for recover glue job role

---

config/prod/usage-statistics-S3.yaml

I added my ARN to the `grantAccess` list in order to get access to this bucket. I believe it contains files related to data usage stats that we need for the AD Portal. Larsson is listed as the bucket owner but has not accessed it himself; he says it's fine for me to be added.

grant bucket access

---

.pre-commit-config.yaml

The mips-api lambda is migrating to a new host name.

Update pre-commit hook to new endpoint

---

config/prod/minidream-rstudio-2023-ec2-alb.yaml
config/prod/minidream-rstudio-2023-ec2.yaml

Setting up a stack to run miniDREAM this year for about 16 students. Similar to [last year](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/522), the stack is composed of a high-memory EC2 instance in a private subnet behind by a public load balancer (both using existing aws-infra templates), which will be used to provide a RStudio environment for students taking the miniDREAM courses.
This PR was built using #522 as a reference.

Create ec2 and alb for miniDREAM 2023

---

DeprecatedProgramCodes.json
config/prod/minidream-rstudio-2023-ec2-alb.yaml
config/prod/minidream-rstudio-2023-ec2.yaml

AWS does not allow parenthesis characters in Tags.
```
validation error detected: Value 'Multi-Consortia Coordinating Center (MC2 Center) / 123100'
at 'tags.3.member.value' failed to satisfy constraint: Member must satisfy regular expression
pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*
```
Remove parenthesis to allow provisioning the resource
for now.  We will need to figure out a more general
solution for this problem.

Remove invalid chars in CostCenter tag

---

config/prod/TESLA-download-bucket.yaml

The template used to provision the TESLA bucket is old and is setup to deploy a lambda with python 3.6. AWS no longer supports that old python version so it fails when we attempt to deploy the bucket with the following message..
```
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported
for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9)
while creating or updating functions.
```
We need to temporarily remove region restriction, update the templates then hopefully restore region restriction.

Remove region restriction for TESLA bucket

---

.yamllint

Restore the yaml quote string check that was removed in PR #567 We want to make sure all values in sceptre config files are quoted.

restore check for quoted string in yaml

---

.pre-commit-config.yaml

The mips-api lambda no longer includes an Other tag by default, so we don't need to ignore it.

Remove unneeded parameter

---

.github/workflows/deploy.yaml

The CI role names to assume will change due to PR
Sage-Bionetworks-IT/organizations-infra#859. update to the new role names
depends on Sage-Bionetworks-IT/organizations-infra#859

[IT-2768] Update role name for CI

---

.pre-commit-config.yaml
DeprecatedProgramCodes.json

MIP Cloud has effectively disabled lambda-mips-api from logging in, roll back to the hard-coded files in aws-infra.
Also add an alternative capitalization for No Program since the hard-coded files have NO PROGRAM.

[IT-2851] Roll back to hard-coded files in aws-infra

---

.pre-commit-config.yaml
DeprecatedProgramCodes.json

MIP Support has resolved the issue preventing the lambda from logging in, return to using it in our pre-commit check.
This reverts commit f6c343e7f6034cd13b74d4cb4231cdf5402c2d1a.

Revert "[IT-2851] Roll back to hard-coded files in aws-infra (#585)"

---

config/prod/minidream-rstudio-2023-ec2.yaml

We are planning on adding about 10 more students to the miniDREAM course, bringing the total number of students to about 26.  To better accommodate the new classroom size, I want to upgrade the instance type and volume size to be the same as last year's, which supported around 27 students without issues.

update instance type and volume size

---

config/prod/s3-synapse-sync.yaml

Only allow access to s3 sync instances from the sage VPN

[IT-2300] Fix AWS security groups in Scicomp

---

config/prod/AMP-Emory-Bucket.yaml
config/prod/PsychENCODE-Globus-S3.yaml
config/prod/TESLA-download-bucket.yaml
config/prod/VEOIBD-S3-USA.yaml
config/prod/dian-prod-hm-migration-s3.yaml
config/prod/dian-uat-hm-migration-s3.yaml
config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml
config/prod/mep-lincs-s3.yaml
config/prod/nf-syn28545963-s3.yaml
config/prod/recover-s3-bucket.yaml
config/prod/usage-statistics-S3.yaml
config/prod/veoibd-s3.yaml

This enables intelligent tiering bucket lifecycle for all buckets deployed to the scicomp account.
The goal is to reduce storage costs.
depends on https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/49

[IT-2923] Enable bucket lifecycle

---

config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml

The release for s3-synapse-sync does not contain a `v` in the release tag[1].
[1] https://github.com/Sage-Bionetworks/s3-synapse-sync/tags

Fix typo in url

---

config/prod/nf-test-s3.yaml
templates/nextflow-tower-s3-bucket.j2

Indications are that nextflow can access the htan-dcc-duke bucket but not the nf-syn* buckets.  Those buckets are setup with different templates.  This is a test to set up a nf-test-s3 bucket using the same template that was used to setup htan-dcc-duke bucket.

[IT-3159] Attempt to fix nextflow access to bucket

---

config/prod/htan-dcc-casi-tnp.yaml

Creating a bucket for HTAN's new CASI TNP atlas. The center will be uploading data to Synapse, so we don't intend to enable the s3_synapse_sync function at this stage.

Create bucket for HTAN CASI TNP project

---

config/prod/psychencode-migration-bucket.yaml

Sage is experiencing $1K-$2K data transfer costs from this bucket.  The change is necessary to prevent excessive ballooning in our AWS bill.

Add Region Restriction to psychencode-migration-bucket

---

config/prod/nda-migration.yaml

This PR updates the NDA migration bucket to incorporate changes to the cloudformation template made in [https://github.com/Sage-Bionetworks/aws-infra/pull/409](https://github.com/Sage-Bionetworks/aws-infra/pull/409).

update cloudformation template URL on NDA migration bucket

---

config/prod/nda-migration.yaml

This PR updates the nda migration bucket to the latest tagged URL for the synapse external bucket template

update synapse-external-bucket url for nda migration bucket

---

config/prod/nda-migration.yaml

This PR removes the region access restriction for the NDA migration bucket

remove region restriction from nda migration bucket

---

config/prod/nda-migration.yaml

This PR adds the region restriction to the NDA migration bucket as a preventative measure to avoid egress.

re-add region restriction to nda migration bucket

---

config/prod/htan-dcc-casi-tnp.yaml
config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml
config/prod/htan-synapse-sync-kms-key.yaml
config/prod/s3-synapse-sync.yaml

This PR makes changes to the User, DenyDelete and Admin ARN lists for HTAN S3 buckets.
It forms part of the offboarding for our colleague @clarisse-lau at ISB who has been an admin on these buckets to date.
Adam Taylor will be added as admin to cover this role until a suitable backfill is onboarded.
Tom Yu remains as admin to provide secondary coverage for this role.
The following changes are made
- Clarisse Lau is removed from the `S3AdminARNs` list
- Adam Taylor is added to the `S3AdminARNs` list
- Adam Taylor is removed from the `S3UserARNs` list as now inherits these permissions from `S3AdminARNs` list
- Adam Taylor is removed from the `S3DenyDeleteARNs` list as delete permissions are required in his `S3AdminARNs`role.
- Owner email is updated to Adam Taylor as Sage HTAN PI, replacing …

Offboarding Clarisse Lau from HTAN buckets

---

config/prod/htan2-testing1.yaml

* Need to add a synapse ID
* It seems like the `IPAddressRestictionLambda` is failing to deploy. We will need to fix it, removing it from this stack for now.
```
[2024-10-18 16:34:58] - prod/htan2-testing1 IPAddressRestictionLambda
AWS::CloudFormation::Stack CREATE_FAILED Embedded stack
arn:aws:cloudformation:us-east-1:***:stack/htan2-testing1-IPAddressRestictionLambda-1534XYHGZI8V8/cd414320-8d6e-11ef-a975-0affca4facf5
was not successfully created: The following resource(s) failed to create: [RestrictBucketDownloadRegionFunction].
```

Fix deployment of htan2-testing s3 bucket

---

DeprecatedProgramCodes.json
config/prod/AMP-Emory-Bucket.yaml
config/prod/PsychENCODE-Globus-S3.yaml
config/prod/aacr-interactome-s3website-new.yaml
config/prod/amp-mayo-sinai.yaml
config/prod/dian-prod-hm-migration-s3.yaml
config/prod/dian-uat-hm-migration-s3.yaml
config/prod/htan-dcc-casi-tnp.yaml
config/prod/htan-dcc-center-a.yaml
config/prod/htan-dcc-chop.yaml
config/prod/htan-dcc-dfci.yaml
config/prod/htan-dcc-duke.yaml
config/prod/htan-dcc-hms.yaml
config/prod/htan-dcc-msk.yaml
config/prod/htan-dcc-ohsu.yaml
config/prod/htan-dcc-pcapp.yaml
config/prod/htan-dcc-stanford.yaml
config/prod/htan-dcc-tma-tnp.yaml
config/prod/htan-dcc-tnp-sardana.yaml
config/prod/htan-dcc-vanderbilt.yaml
config/prod/htan-synapse-sync-kms-key.yaml
config/prod/htan2-testing1.yaml
config/prod/nf-syn23664726-s3.yaml
config/prod/nf-syn28545963-s3.yaml
config/prod/nf-test-s3.yaml
config/prod/s3-synapse-sync.yaml

The cost center codes that were in the deprecation list are actually
valid.  The codes matach up to codes from finance, the description
portion was not exactly the same.  Update to match the ones from
finance exactly.

Update deprecated program codes

---

config/prod/cmc-migration-bucket.yaml
config/prod/psychencode-migration-bucket.yaml

The Psychencode DACC needs to download roughly 2 TB of data from the CMC and PEC project, but they do not have access to AWS. This PR removes the region restriction to allow for the DACC to complete a key final step of the migration from Synapse. Egress cost should be minimal for this download (~$180), and only a few select number of users still have access to these projects on Synapse.

remove region restriction from PEC and CMC buckets

---

config/prod/cmc-migration-bucket.yaml
config/prod/psychencode-migration-bucket.yaml

This PR re-introduces the same-region transfer restriction to the CMC and PEC migration buckets that was removed in #658. The PsychEncode DACC has downloaded the files that they need locally, so we should add the restriction back to these buckets to prevent egress.

add AWS transfer restriction to PEC and CMC buckets

---

config/prod/nda-migration.yaml

The Problem: I need to copy files between two S3 buckets that belong to two different AWS accounts. The first bucket was created using the strides service catalog under the Synapse service account  'synapse-service-psychencode-migration'. The second bucket was created using the scicomp provisioner (https://github.com/wpoehlm/scicomp-provisioner/blob/master/config/prod/nda-migration.yaml). 
The Solution: This PR adds the user ARN for the service account user 'synapse-service-psychencode-migration' to the nda-migration bucket. This will allow me to authenticate the service account directly in the Service Catalog, which will also now have direct access to the 'nda-migration' bucket.

add psychencode migration service account to nda-migration bucket

---

config/prod/nda-migration.yaml

This PR adds two new ARNs to the nda migration bucket:
arn:aws:iam::618523879050:role/NdaCsvProcessorStack-NdaCsvProcessorWorkerLambdaabc-glTdCT6jNYFa
arn:aws:iam::517707202846:role/NdaCsvProcessorStack-NdaCsvProcessorWorkerLambdanda-TsdSKtGz9yVZ
These ARNs were provided by NDA and are required to complete the final Psychencode data migration

add NDA arns for final PEC migration

---

config/prod/cmc-migration-bucket.yaml

The Psychencode/CMC migration team discovered one file that failed to transfer from the CMC bucket previously. To allow them to download this file and complete the migration to NDA, I am removing the region restriction from the CMC bucket temporarily.

remove region restriction from cmc bucket
